stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "docker:20.10.21"
  REGISTRY: "registry.gitlab.com/chuducanh242002/devops-gitlab"
  DOCKER_TAG: $REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $REGISTRY

build:
  stage: build
  script:
    - docker build -t $DOCKER_TAG .
    - docker push $DOCKER_TAG
  tags:
    - token1

test:
  stage: test
  script:
    - docker pull $DOCKER_TAG
    - docker run --rm -d -p 8080:80 --name nginx-test $DOCKER_TAG
    - sleep 5
    - curl -f http://localhost:8080 || exit 1
    - docker stop nginx-test
  tags:
    - token1

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_TAG
    - docker stop nginx-app || true
    - docker rm nginx-app || true
    - docker run -d -p 80:80 --name nginx-app $DOCKER_TAG
  tags:
    - token1
