version: '2.20.2'

services:
  service1:
    image: service1
    container_name: service1_container
    build: ./service1
    ports:
      - "8199:8199"
    depends_on:
      - service2
  service2:
    image: service2
    container_name: service2-container
    build: ./service2
    # ports:
    #   - "3000:3000"