version: '3'

services:
  service1_instance1:
    build: ./service1
    container_name: service1_instance1
  service1_instance2:
    build: ./service1
    container_name : service1_instance2
  service1_instance3:
    build: ./service1
    container_name : service1_instance3
  service2:
    image: service2
    container_name: service2-container
    build: ./service2
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "8198:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - service1_instance1
      - service1_instance2
      - service1_instance3

  tests:
    build: ./tests
    container_name: tests
    volumes:
      - ./tests:/tests
      - ./service1/app.py:/service1/app.py  # Mount service1 code
    working_dir: /tests
    command: pytest
    depends_on:
      - service1_instance1